# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/microprocessor/microprocessor.srcs/sources_1/ip/blk_mem_ROM/blk_mem_ROM.xci
# IP: The module: 'blk_mem_ROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/microprocessor/microprocessor.srcs/sources_1/ip/blk_mem_ROM/blk_mem_ROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_ROM'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: e:/microprocessor/microprocessor.srcs/sources_1/ip/blk_mem_ROM/blk_mem_ROM.xci
# IP: The module: 'blk_mem_ROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/microprocessor/microprocessor.srcs/sources_1/ip/blk_mem_ROM/blk_mem_ROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_ROM'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
