# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Alex/Documents/GitHub/ECE320_Project/microprocessor.srcs/sources_1/ip/blk_mem_RAM/blk_mem_RAM.xci
# IP: The module: 'blk_mem_RAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Alex/Documents/GitHub/ECE320_Project/microprocessor.srcs/sources_1/ip/blk_mem_RAM/blk_mem_RAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_RAM'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/Alex/Documents/GitHub/ECE320_Project/microprocessor.srcs/sources_1/ip/blk_mem_RAM/blk_mem_RAM.xci
# IP: The module: 'blk_mem_RAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Alex/Documents/GitHub/ECE320_Project/microprocessor.srcs/sources_1/ip/blk_mem_RAM/blk_mem_RAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_RAM'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
